### ISSUE TITLE
service('foo') is not transformed properly

### ISSUE THREAD

**Issue by lukemelia** [ember-codemods/ember-native-class-codemod#148]
In my app, the following property:

```
errorService: service('error')
```

was transformed to:

```
@service
errorService;
```

which are not equivalent. The correct output should be:

```
@service('error')
errorService;
```

**Comment by lukemelia** [comment]
This may be related to https://github.com/ember-codemods/ember-native-class-codemod/issues/141

**Comment by pzuraq** [comment]
This should be fixed on master, will be cutting a release soon!
