### ISSUE TITLE
Computed Modifiers

### ISSUE THREAD

**Issue by pzuraq** [ember-codemods/ember-native-class-codemod#15]
Summarizing various conversations we've had on this topic in this issue, pretty sure everyone is in alignment on the path forward. 

In Ember today, computed properties can have modifiers which change the behavior of the computed:

```js
foo: computed('bar', function() { /*...*/ })
  .readOnly() // makes the computed read only (throw on set)
  .volatile() // makes the computed volatile (recomputed each time)
  .property('baz') // adds additional dependent keys to the computed
  .meta({ type: 'Property' }); // adds metadata to the computed
```

These modifiers could be chained in any order on an instance of a computed property. However, they are not fully supported by ember-decorators yet, so we have to decide on an API to target.

Some additional constraints:

1. Decorators can only consist of A) a chain of identifiers with a final function call invocation at the very end or B) an arbitrary expression surrounded by parentheses:

   ```js
   // valid
   @foo
   @foo.bar 
   @foo()
   @foo.bar()
   @(foo().bar)
   @(foo().bar())

   // invalid
   @foo().bar
   @foo().bar()
   ```

2. We don't want to lean too heavily on the ability to use expressions in parens, because it is more verbose, harder to read, and is counter to our long term goal of making Ember feel like JS
3. `property` and `meta` will require expressions no matter what because they take parameters, but they are very very rare use cases. `property` only makes sense for computed macros (otherwise the dependent key could be added to the `computed()` call) and `meta` is only known to be used by Ember Data.
4. We want the new system to be fairly intuitive to users of the old system

With that in mind, the proposal is the following:

```js
// INPUT
foo: computed('bar', function() {}).readOnly()

// OUTPUT
// readOnly is very commonly used, so not requiring expression syntax here is good.
@computed.readOnly('bar') get foo() {}

// INPUT
foo: alias('bar').readOnly()

// OUTPUT
@alias.readOnly('bar') foo;

// INPUT
foo: computed('bar', function() {}).volatile()

// OUTPUT
// volatile is fairly commonly used, so not requiring expression syntax here is good.
// Dependent keys are meaningless to volatile computeds, so they can be removed
@computed.volatile() get foo() {} 

// INPUT
foo: computed('bar', function() {}).readOnly().volatile()

// OUTPUT
// volatile getters behave the same as native getters, and because the property is readOnly 
// we can know without a doubt that it can be replaced safely with a native getter. This 
// prevents us from having to support chaining in non-expression computed usage
get foo() {} 

// INPUT
foo: alias('bar').property('baz')

// OUTPUT
// requires expression syntax due to params
@(alias('bar').property('baz')) foo;

// INPUT
foo: computed('bar', function() {}).meta({ type: 'Property' })

// OUTPUT
// requires expression syntax due to params
@(computed('bar').meta({ type: 'Property' })) get foo() {}
```

`volatile` generally doesn't make sense with macros, so we shouldn't have to account for that situation. `property` and `meta` should be chainable in any order, and should be able to chain off of `readOnly` and `volatile` as well.

**Comment by ssutar** [comment]
@pzuraq  Should we error out when we encounter `volatile` with  macros or just remove the `volatile` and proceed to transform the object?

**Comment by ssutar** [comment]
@pzuraq Another issue I see is how do we transform the below expression
```
  /**
   * Fname2
   */
  fName2: computed("firstName", "lastName", function() {
    return true;
  })
    .property("baz")
    .readOnly()
    .volatile()
    .meta({ type: "Property" }),
```
Essentially it has `volatile` and `readOnly` along with other modifiers. I think we should keep all the modifiers in this case. Something like:
```
  /**
   * Fname2
   */
  @(
    computed("firstName", "lastName").property("baz").readOnly().volatile().meta({ type: "Property" })
  )
  get fName2() {
    return true;
  }
```
This brings up a question - does it makes sense for `codemods` to actually care about issues such as, having `readOnly` and `volatile` together or `volatile` being applied on macros? 🤔 Should it be handled by `eslint` rules?

**Comment by pzuraq** [comment]
> Should we error out when we encounter volatile with macros or just remove the volatile and proceed to transform the object?

I think we should error, this shouldn't happen and if it does we'll probably want the user to figure it out themselves.

For the expression you're showing, we don't want users to get confused with `readOnly` and `volatile`, so we won't support chainable versions of them in the decorators. The only way to use them will be before the expression call (e.g. `computed.volatile()` and `computed.readOnly()`). 

If we have `readOnly` + `meta` or `readOnly` + `property` they can chain after:

```js
@(computed.readOnly().meta().property())
```

`volatile` and `property` cancel each other out, there's no point to adding dependent keys to a property so it won't happen. That leaves one combination which can't be handled by the codemode:

```
foo: computed().readOnly().volatile().meta()
```

Since `meta` is very rarely used as is, I think for now we should error if this happens, and hopefully we'll never encounter it. If we do, we can revisit the public API to add chainable readOnly/volatile somehow then.

**Comment by ssutar** [comment]
These 2 are different issues:

The first one
> Should we error out when we encounter volatile with macros or just remove the volatile and proceed to transform the object?

This refers to the 
> volatile generally doesn't make sense with macros, so we shouldn't have to account for that situation.

in the issue description

Which means if we encounter something like
```
foo: sum('a', 'b').volatile()
```
Should we error out?


The second issue is about whether to fix the `readOnly().volatile()` with native `getter` or leave it to other tools like `eslint` to report and let users fix it. 

I personally would like to leave it `eslint` as it would be cleaner in terms of responsibilities and you'll have the recommended rule to not to use `readOnly` and `volatile` together even if you don't use codemods.

**Comment by pzuraq** [comment]
Yup, I meant to respond to both separately, sorry that didn't come across 😅 

> Which means if we encounter something like
> ```
> foo: sum('a', 'b').volatile()
> ```
> Should we error out?

Yes, we should. I do not think we should support this.

For the 2nd issue, the problem is we would rather not support the ability to use `readOnly` and `volatile` together in ember-decorators with the current API design:

```js
@(computed().volatile().readOnly()) // will not work
```

Instead, it would be better to replace with a native getter if we encounter this. This would cover the majority of possible permutations, and the only one which would _not_ be supported is `computed().volatile().readOnly().meta()` which is very, very unlikely to ever occur, so it's an acceptable risk to throw an error on it.

**Comment by ssutar** [comment]
Thanks @pzuraq 

For the 2nd issue - if we don't want to support that then I think it is okay to do the transform to native `getter`. That way we don't have it supported in the future. I think we should mention as a note in the readme.

**Comment by ssutar** [comment]
Updated https://github.com/scalvert/ember-es6-class-codemod/pull/16

**Comment by ssutar** [comment]
Thanks @pzuraq  I can quickly change to error those out!!

**Comment by ssutar** [comment]
Done - Updated #16
