### ISSUE TITLE
Make codemod target classes generically

### ISSUE THREAD

**Issue by pzuraq** [ember-codemods/ember-native-class-codemod#3]
Currently the codemod targets only calls to `EmberObject.extend` specifically, which excludes any subclasses of `EmberObject` including Ember concepts (Services, Routes, Components, etc).

We should be able to target any calls to `.extend`, but to be safe we can also scope it CapitalCased elements:

```js
// transformed
FooClass.extend({});

// ignored
fooClass.extend({});
$.extend();
```

**Comment by ssutar** [comment]
Thanks @pzuraq !

@scalvert and I were discussing about this. We were thinking about making this configurable to make it easier to roll out on a large codebase. 

Specifically we were thinking to have an ability transform only specific object like `services` or `controllers`. This way users can run the codemods in iterations. For example, `services` in the first pass. `controllers` in another. 

Additionally we were thinking about having options to exclude/include certain objects - like target objects which does not have any decorators. 

Would love to hear your thoughts!

**Comment by pzuraq** [comment]
Hmm, I wonder if we should have it be scoped by identifier, or by file path. Would it make sense to want to convert half of a file?

For instance, if we ran the codemod on just `Controller` then only half of this example would be converted:

```js
const UtilityClass = EmberObject.extend({
  // ...
});

export default Controller.extend({
  // ...uses utility class 
});
```

Would that be more desirable, or would it be better to convert the entire file at once and allow users to scope by saying `--include '/app/controllers/**/*'`

For decorators vs. not-decorators, completely agree. This would essentially be the difference between stage-3+ and stage-2+, and could probably be a command line option (with the default being stage-3+).

**Comment by ssutar** [comment]
https://github.com/scalvert/ember-es6-class-codemod/pull/12
