### ISSUE TITLE
Transforms templates sometimes..

### ISSUE THREAD

**Issue by knownasilya** [ember-codemods/ember-native-class-codemod#50]
I ran this on a fairly sizable project (it transformed 309 files). Two of those files were templates. Here are the changes that were made:

<img width="732" alt="screen shot 2019-01-16 at 5 07 21 pm" src="https://user-images.githubusercontent.com/34726/51281740-4dff6600-19b1-11e9-9f39-5075c6e68bb1.png">
<img width="1145" alt="screen shot 2019-01-16 at 5 08 00 pm" src="https://user-images.githubusercontent.com/34726/51281741-4dff6600-19b1-11e9-8428-998fc1ab53f4.png">

I ran the following command:

```sh
ember-es6-class-codemod ember-object --decorators=true app/**
```

**Comment by pzuraq** [comment]
We should probably ignore any non `.js` files (maybe we can transform `.ts`?)

**Comment by pzuraq** [comment]
This should be fixed on master it looks like, let us know if it isn't!
