### ISSUE TITLE
Duplicate declarations

### ISSUE THREAD

**Issue by knownasilya** [ember-codemods/ember-native-class-codemod#51]
```
Build Error (broccoli-persistent-filter:Babel > [Babel: mldp]) in mldp/account/action/controller.js

/Users/iradchenko/workspace/lma/src/MLDP.WebApp/mldp/account/action/controller.js: Duplicate declaration "Controller"
  3 | import { service } from "@ember-decorators/service";
  4 |
> 5 | export default class Controller extends Controller {
    |                      ^
  6 |   @service('notifications')
  7 |   notifications;
  8 |
```

**Comment by pzuraq** [comment]
Ah, I don't think we handled pod/MU style declarations of names, @ssutar we definitely should add this functionality (also PRs definitely welcome! 😄)

**Comment by knownasilya** [comment]
I'd contribute if I even understood how this thing worked. Where is the code? Haha!

**Comment by knownasilya** [comment]
Looks like the code is here: https://github.com/scalvert/ember-es6-class-codemod/blob/master/transforms/helpers/parse-helper.js#L477

Do we have pods code anywhere? Will the testing layout need changes like mimicking pods?

**Comment by pzuraq** [comment]
I don’t believe any pods code exists yet, and we definitely will need new tests/fixtures that mimic the pods structure. I think the new tests should be pretty straightforward, basically an input directory and output directory, though I’m not sure if our tests handle directories yet

**Comment by ssutar** [comment]
@pzuraq Isn't this same as https://github.com/scalvert/ember-es6-class-codemod/pull/49 where we would append the class type. So this would become 
```
export default class ControllerController extends Controller
```
which is not a good name but is valid

**Comment by pzuraq** [comment]
In the pods/MU style, the information is one level up, the folder name that contains the file:

```
/MLDP.WebApp/mldp/account/action/controller.js:
```

Should output:

```js
export default ActionController extends Controller {}
```

I think folks may want this to be even less generic, like `AccountActionController`, but I don't think that's something we can automate, so probably just the single enclosing folder is the best thing to add to the class name.

**Comment by pzuraq** [comment]
This should be fixed on master, let us know if you're still having issues!
