### ISSUE TITLE
Reopen name is lowercase

### ISSUE THREAD

**Issue by knownasilya** [ember-codemods/ember-native-class-codemod#54]
```js
class PageHeadComponent extends Component {
  // truncated
}

pageHeadComponent.reopenClass({
  positionalParams: ['title']
});

export default pageHeadComponent;
```

**Comment by ssutar** [comment]
It can be solved in 2 ways

1. Not capitalize the class name in case its not immediate `export` or `export default`. In other words keep the variable name as is
```
class pageHeadComponent extends Component {
  // truncated
}

pageHeadComponent.reopenClass({
  positionalParams: ['title']
});

export default pageHeadComponent;
``` 
2. Capitalize the class name and all its occurrences.

I would prefer option 1 as its straightforward and would not have any undesired consequences.

**Comment by pzuraq** [comment]
I think we should capitalize the class name and all occurrences, this is what users will likely expect as output

**Comment by pzuraq** [comment]
This should be solved now, I'm adding a test on master but the class naming logic will now leave any variable name that already exists alone. It'll only add a name if the name did not previously exist.
