### ISSUE TITLE
Service import incorrect

### ISSUE THREAD

**Issue by rwwagner90** [ember-codemods/ember-native-class-codemod#59]
Currently, the import transform for services is incorrect.

```js
import { inject as service } from '@ember/service';
```

is replaced with:

```js
import { service } from "@ember-decorators/service";
```

I believe it should be:

```js
import { inject as service } from "@ember-decorators/service";
```

**Comment by ssutar** [comment]
Thanks @rwwagner90 The codemods need to be updated as per changes in ember-decorators. It should handle `controller` import as well. http://ember-decorators.github.io/ember-decorators/docs/api/modules/@ember-decorators/controller

**Comment by pzuraq** [comment]
This has been fixed
