### ISSUE TITLE
class RouterRouter extends EmberRouter

### ISSUE THREAD

**Issue by pzuraq** [ember-codemods/ember-native-class-codemod#64]
When transforming the Router with telemetry, it appends the type to the class name, which is incorrect.

**Comment by ssutar** [comment]
What is the `file name` and `type` returned from the telemetry? As per the code we append the type to file name. This would happen if file name is `router.js` and telemetry type is `router` 

I am not sure how much we can automate the class naming. Sometimes I think we should have a different `codemod` just to handle the naming of classes, given the different cases in naming an unnamed class 😄

**Comment by pzuraq** [comment]
I think that falls within the domain of this codemod. We're trying to create the best experience possible for anyone updating an Ember app to to native class syntax, so figuring out the naming is part of that. This is something that should be scoped in nature, since Ember apps have strong conventions here. There are a finite number of edge cases to handle 😃 

In this case, there is only one `router.js`, so we should ignore it. This was also a larger problem, because it transpiled to the following:

```js
import { get } from '@ember/object';
import { scheduleOnce } from '@ember/runloop';
import { inject as service } from '@ember/service';
import EmberRouter from '@ember/routing/router';
import config from './config/environment';
import RouterScroll from 'ember-router-scroll';

class RouterRouter extends EmberRouter.extend(RouterScroll) {
}

Router.map(function() {
});

export default Router;
```

Which broke, since only one of the symbols was transformed.

**Comment by pzuraq** [comment]
Ah, I think that would be reasonable, separate them out structurally. They probably don't have to be completely separate codemods, just functions run sequentially in the same codemod, e.g. after this: https://github.com/ember-codemods/ember-es6-class-codemod/blob/master/transforms/ember-object/index.js#L17
